const http = require('http');

const server = http.createServer ( (req, res) => {
    console.log("log generated by index file from node app");
    res.write("Welcome to the NODE App");
    res.end();
});

// server.listen(3000);
server.listen(3000); // PORT is a variable name
// setting end port to 3000 hard codes it to 3000
// (we can have any source but end port has to be 3000). 
//The above avoids this.

/*
npm init
*/